[Feature] Levenshtein Command Matching
biscuitlang/bl pull request #181
Opened 2023-11-23 16:37 UTC by GmosNM

This pull request introduces a new feature: levenshtein command matching. The goal is to enhance the command-line interface by allowing approximate command matching using the Levenshtein distance algorithm.

2023-11-23 18:48 UTC, travisdoor requested changes

2023-11-23 18:48 UTC, travisdoor commented on src/main.c
> +s32 levenshtein_distance(const char *s1, const char *s2) {
There is already implementation for this in `common.h` + `make_str_from_c` macro to convert to `str_t`.

2023-11-23 18:48 UTC, travisdoor commented on src/main.c
> +const char *compute_command(const char *command) {
Local C functions like this should be `static`.

2023-11-23 18:48 UTC, travisdoor commented on src/main.c
> +const char *compute_command(const char *command) {
Name `compute_command` is not too much descriptive, **mainly it's not command**, but command argument. I would use something like `find_closest_argument`.

2023-11-23 18:48 UTC, travisdoor commented on src/main.c
> +	const char *commands[4] = {
Why is this hard coded to use just these? You can check all possible arguments by providing `struct getarg_opt *opts`.

2023-11-23 18:48 UTC, travisdoor commented on src/main.c
> +	const s32 num_commands = sizeof(commands) / sizeof(commands[0]);
There is macro for this `static_arrlenu`.

2023-11-23 18:48 UTC, travisdoor commented on src/main.c
> +		builder_error("Did you mean '%s'?", closest_command);
Either join the hint message with "Unknown argument ..." report or use `builder_info`. This way the hint has `error` prefix event if it's not an error.

2023-11-23 21:36 UTC, travisdoor requested changes

2023-11-23 21:36 UTC, travisdoor commented on src/main.c
> +s32 levenshtein_distance(str_t *s1, str_t *s2) {
There is `s32   levenshtein(const str_t s1, const str_t s2);` in `common.h`.....

2023-11-23 21:36 UTC, travisdoor commented on src/main.c
> +static const char *find_closest_argument(struct getarg_opt *opts, str_t *command) {
`command` -> `opt`

2023-11-23 21:36 UTC, travisdoor commented on src/main.c
> +		struct getarg_opt *cached_opt = opts;
`cached_opt` -> `cached_opts`

2023-11-24 12:06 UTC, travisdoor requested changes

2023-11-24 12:06 UTC, travisdoor commented on src/main.c
> +		int distance = levenshtein(opt, make_str_from_c(current_opt->name));
`int` -> `s32`

2023-11-24 12:06 UTC, travisdoor commented on src/main.c
> +		const char *closest_command = find_closest_argument(cached_opts, make_str_from_c(arg));
`closest_command` -> `closest_arg`

2023-11-24 12:06 UTC, travisdoor commented on src/main.c
> +		const char *closest_command = find_closest_argument(cached_opts, make_str_from_c(arg));
When you're renaming things, please do it everywhere...

2023-11-26 18:21 UTC, travisdoor requested changes

2023-11-26 18:21 UTC, travisdoor commented on src/common.c
> +	s64 score   = 0;
If I understood correctly, this value is more likely `distance` than `score` because a lower means a closer match?

2023-11-26 18:21 UTC, travisdoor commented on src/common.c
> +			score += 2;
Why +2 ?

2023-11-26 18:27 UTC, GmosNM commented on src/common.c
> +	s64 score   = 0;
correct i forgot to change it i was doing some tests

2023-11-28 23:37 UTC, travisdoor requested changes
Hey, it works surprisingly well :). The only improvement I was thinking about was figuring out some limits to say, "ok, this suggestion is completely wrong, and we should not print it". To somehow workaround cases like `Unknown argument '-mir', did you mean '--dirty-mode'?`. Any ideas? In such a case no suggestion is IMHO better than a completely wrong suggestion.

2023-11-28 23:37 UTC, travisdoor commented on src/common.c
> +str_t trim_leading_character(str_t str, u8 c) {
Maybe `trim_leading_characters` if it removes all of them from the beginning?

2023-11-28 23:37 UTC, travisdoor commented on src/common.c
> +	str   = trim_leading_character(str, '-');
These should not be there if this function is public to the rest of the compiler; you should not modify the input here.

2023-11-28 23:37 UTC, travisdoor commented on src/common.c
> +	s32 min_len = (str.len < other.len) ? str.len : other.len;
There is a macro `MIN` for this.

2023-11-28 23:37 UTC, travisdoor commented on src/common.c
> +s64 fuzzy_cmp(str_t str, str_t other) {
I was thinking about `s32`, which is probably enough in this case.

2023-11-28 23:37 UTC, travisdoor commented on src/common.c
> +	s32 min_len = (str.len < other.len) ? str.len : other.len;
Also, the variable can be `const`.

2023-12-07 20:10 UTC, travisdoor requested changes
Hi, this is still a bit broken. Now I have no suggestion for input e.g.: `--full-poth`. It should be `--full-path`. I tried to debug it, and it stopped searching for a comparison against `-run` option. The `distance` is 0 in this case, and `find_closest_argument` returns.

2023-12-10 11:30 UTC, travisdoor requested changes

2023-12-10 11:30 UTC, travisdoor commented on src/main.c
> +	struct closest_opt_t *closest_opts  = NULL;
We use stb dynamic arrays in the compiler. https://github.com/travisdoor/bl/blob/2f2f6e9d2938200db3a6e37e1a271a728a2339e9/src/stb_ds.h#L69

2023-12-10 11:30 UTC, travisdoor commented on src/main.c
> +	struct closest_opt_t *closest_opts  = NULL;
Dynamic array definition should be wrapped into `array(T)` macro; this way it's easier to see its dynamic array not just a pointer to something; e.g: `array(struct closest_opt_t*) closest_opts = NULL;`

2023-12-10 11:30 UTC, travisdoor commented on src/main.c
> +			closest_opts             = realloc(closest_opts, closest_count * sizeof(struct closest_opt_t));
Here, you should use `arrput` macro from `stb`; generally, memory allocation API is centralized in `bmemory.h` (`brealloc` `bmalloc` `bfree`). This way we can easily control which allocator is used under the hood + we can track the memory usage eventually.

2023-12-10 11:30 UTC, travisdoor commented on src/main.c
> +struct closest_opt_t {
A bit nitpicking :) `_t` suffix is not needed, type name is in the `struct` namespace. I use `_t` suffix only for typedefs.

2023-12-10 11:30 UTC, travisdoor commented on src/main.c
> +	free(closest_opts);
`arrfree` here

2024-07-01 16:50 UTC, closed without merging